// Croatian for everything the model can put on screen. The engine stays in
// English internally, so this is a display layer and nothing else: swapping
// language cannot change a life.

const HR = {

  // ---- što se radi -------------------------------------------------------
  "sleeping": "spavanje",
  "being carried": "nošenje na rukama",
  "crying": "plakanje",
  "staring at the lamp": "gledanje u lampu",
  "eating": "jelo",
  "putting it in your mouth": "stavljanje svega u usta",
  "laughing at nothing": "smijanje bez razloga",
  "being put down again": "opet spuštanje u krevetić",
  "running": "trčanje",
  "asking why": "pitanje zašto",
  "drawing a house": "crtanje kuće s dimom iz dimnjaka",
  "breaking something": "razbijanje nečega",
  "watching cartoons": "gledanje crtića",
  "riding a bike": "vožnja bicikla",
  "collecting stones": "skupljanje kamenčića",
  "lying about homework": "laganje o zadaći",
  "playing until it is dark": "igranje do mraka",
  "being bored": "dosada",
  "staying up too late": "predugo ostajanje budnim",
  "arguing": "svađanje",
  "listening to the same song": "slušanje iste pjesme",
  "being embarrassed": "sram",
  "studying the night before": "učenje noć prije",
  "slamming a door": "zalupljivanje vratima",
  "looking in the mirror": "gledanje u ogledalo",
  "loving someone who does not know": "voljeti nekoga tko ne zna",
  "saying nothing at dinner": "šutnja za stolom",
  "working": "posao",
  "working, still": "posao, i dalje",
  "moving out": "selidba",
  "falling in love": "zaljubljivanje",
  "going somewhere cheap": "putovanje nekamo jeftino",
  "drinking too much": "previše pića",
  "starting something": "započinjanje nečega",
  "quitting something": "odustajanje od nečega",
  "applying": "slanje prijava",
  "waiting for an answer": "čekanje odgovora",
  "calling home, briefly": "kratki poziv doma",
  "fixing the same thing again": "opet popravljanje istoga",
  "worrying about money": "briga oko novca",
  "driving somewhere": "vožnja nekamo",
  "answering messages": "odgovaranje na poruke",
  "carrying something heavy": "nošenje nečega teškog",
  "cancelling": "otkazivanje",
  "being needed": "biti nekome potreban",
  "seeing fewer friends": "sve rjeđe viđanje prijatelja",
  "sleeping badly": "loše spavanje",
  "looking after someone": "briga o nekome",
  "going to funerals": "odlasci na sprovode",
  "walking for the sake of it": "šetnja bez razloga",
  "reading the news too closely": "prečitavanje vijesti",
  "having the same argument": "ista svađa",
  "putting something aside": "odvajanje sa strane",
  "standing in the doorway of a room": "stajanje na vratima sobe",
  "walking slowly": "polagano hodanje",
  "reading the same page twice": "čitanje iste stranice dvaput",
  "watering the plants": "zalijevanje cvijeća",
  "watching the news": "gledanje vijesti",
  "waiting for the phone": "čekanje da telefon zazvoni",
  "telling the story again": "opet ista priča",
  "sitting in the sun": "sjedenje na suncu",
  "going to the doctor": "odlazak liječniku",
  "sitting": "sjedenje",
  "being visited": "posjeti",
  "waiting": "čekanje",
  "sleeping in the afternoon": "popodnevno spavanje",
  "not recognising the street": "neprepoznavanje ulice",
  "looking at photographs": "gledanje fotografija",
  "carrying someone who is asleep": "nošenje nekoga tko je zaspao",
  "reading the same book aloud": "čitanje iste knjige naglas",
  "worrying about someone else": "briga za nekoga drugog",

  // obveze
  "being fed": "hranjenje",
  "going to school": "škola",
  "doing the homework": "zadaća",
  "handing it in": "predaja zadaće",
  "explaining yourself": "objašnjavanje",
  "going to work": "odlazak na posao",
  "paying the bill": "plaćanje računa",
  "answering the message": "odgovor na poruku",
  "renewing the documents": "produljenje dokumenata",
  "taking the bins out": "iznošenje smeća",
  "getting it repaired": "popravak",
  "taking the pills": "tablete",
  "going to the check-up": "kontrolni pregled",

  // ono što se ne bi smjelo
  "checking the phone at three in the morning": "mobitel u tri ujutro",
  "saying it out loud": "izgovaranje naglas",
  "comparing": "uspoređivanje",
  "keeping score": "brojanje tuđih grešaka",
  "reading the comments": "čitanje komentara",
  "replying immediately": "odgovaranje odmah",
  "looking back too long": "predugo osvrtanje",
  "having one more": "još jedno piće",
  "bringing it up again": "opet spominjanje toga",

  // godišnja doba i more
  "keeping warm": "grijanje",
  "waiting for it to get light": "čekanje da se razdani",
  "staying in": "ostajanje unutra",
  "opening the windows": "otvaranje prozora",
  "being outside again": "opet vani",
  "sitting in the shade": "sjedenje u hladu",
  "going to the water": "odlazak na vodu",
  "lying awake in the heat": "budnost u vrućini",
  "going back to it": "povratak na posao",
  "watching it get dark early": "rano smrkavanje",
  "being at the sea": "more",
  "doing nothing, on purpose": "namjerno ništa",
  "reading half a book": "pola knjige",
  "eating outside": "jelo vani",

  // ono što svijet donese
  "listening for news": "osluškivanje vijesti",
  "queueing": "stajanje u redu",
  "counting it again": "ponovno prebrojavanje",
  "going without": "snalaženje bez",
  "looking for work": "traženje posla",
  "staying put": "ostajanje gdje jesi",
  "going to look at it": "odlazak da se to vidi",
  "sending what you can": "slanje koliko se može",
  "listening for the all-clear": "čekanje znaka da je gotovo",
  "boarding up the windows": "zabijanje dasaka na prozore",
  "carrying things upstairs": "nošenje stvari na kat",
  "drying it out": "sušenje svega",
  "sleeping in the car": "spavanje u autu",
  "sitting in the dark with the shutters closed": "sjedenje u mraku sa spuštenim roletama",
  "keeping one room warm": "grijanje jedne sobe",
  "staying indoors": "ostajanje unutra, cijelu godinu",
  "going the new way": "novi put",
  "walking it instead": "hodanje umjesto toga",

  // ono što je od škole ostalo
  "long division": "dijeljenje s ostatkom",
  "the other language, badly": "onaj drugi jezik, loše",
  "how to look busy": "kako izgledati zauzeto",
  "the word for window": "riječ za prozor",
  "how to sit through things": "kako izdržati do kraja",

  // ---- misli -------------------------------------------------------------
  "the ceiling": "strop",
  "that face again": "opet ono lice",
  "hunger": "glad",
  "warm": "toplo",
  "the sound of the door": "zvuk vrata",
  "being put down": "spuštanje",
  "what is under the bed": "što je pod krevetom",
  "why the sky": "zašto nebo",
  "Saturday": "subota",
  "the smell of the hallway": "miris haustora",
  "whether they saw": "jesu li vidjeli",
  "what they said about you": "što su rekli o tebi",
  "being allowed to stay out": "hoće li te pustiti van",
  "what you said in the corridor": "što si rekao na hodniku",
  "whether they meant it": "jesu li to mislili ozbiljno",
  "the same song": "ista pjesma",
  "getting out of here": "otići odavde",
  "your own face": "vlastito lice",
  "nothing, loudly": "ništa, glasno",
  "the rent": "najamnina",
  "they said 'sure', not 'yes'": "rekli su „može”, ne „da”",
  "whether this is the job": "je li ovo taj posao",
  "it is August already": "već je kolovoz",
  "what you said in 2009": "što si rekao 2009.",
  "calling home": "nazvati doma",
  "the noise the knee makes": "zvuk koji koljeno ispušta",
  "the bill due on the eleventh": "račun dospijeva jedanaestog",
  "that meeting could have been an email": "taj sastanak mogao je biti mail",
  "everyone in this photograph is older now": "svi na ovoj fotografiji sada su stariji",
  "whether they are all right": "jesu li dobro",
  "who is left": "tko je još ostao",
  "what it used to cost": "koliko je to prije koštalo",
  "whether they will call": "hoće li nazvati",
  "the stairs": "stepenice",
  "what it used to be": "što je ovdje prije bilo",
  "whether it makes any difference": "mijenja li to išta",
  "the stairs in the dark": "stepenice u mraku",
  "being the last one collected": "biti zadnji po kojeg dolaze",
  "water, further out than you thought": "voda, dublja nego što si mislio",
  "a door you cannot find in a house you know": "vrata koja ne možeš naći u kući koju znaš",
  "your own name, said wrong": "vlastito ime, krivo izgovoreno",
  "the light in a hospital corridor": "svjetlo u bolničkom hodniku",

  // ---- teme --------------------------------------------------------------
  "home": "dom", "love": "ljubav", "body": "tijelo", "fear": "strah",
  "time": "vrijeme", "shame": "sram", "money": "novac", "work": "posao",
  "death": "smrt", "politics": "politika",

  // ---- popis koji si namjeravao -----------------------------------------
  "call your mother": "nazvati mamu",
  "sleep more": "više spavati",
  "get it looked at": "dati to pogledati",
  "learn the other language properly": "naučiti onaj jezik kako treba",
  "write it down": "zapisati",
  "forgive him": "oprostiti mu",
  "throw out the boxes": "baciti kutije",
  "say it while there is time": "reći dok ima vremena",
  "go outside": "izaći van",
  "read the book you bought": "pročitati knjigu koju si kupio",
  "fix the tap": "popraviti slavinu",
  "apologise properly": "ispričati se kako treba",
  "find out what happened to Marko": "saznati što je bilo s Markom",
  "stand up straight": "uspraviti se",

  // ---- svijet ------------------------------------------------------------
  "the government falls": "vlada pada",
  "a new government, much like the last": "nova vlada, slična prošloj",
  "the currency is reformed": "mijenja se valuta",
  "prices double, and then double": "cijene se udvostruče, pa opet",
  "the factory closes": "tvornica se zatvara",
  "the border closes": "granica se zatvara",
  "the border opens": "granica se otvara",
  "war, somewhere else": "rat, negdje drugdje",
  "war, here": "rat, ovdje",
  "the river takes the lower streets": "rijeka odnosi donje ulice",
  "an earthquake, in the night": "potres, noću",
  "the summer that would not end": "ljeto koje nije prestajalo",
  "a winter with no coal": "zima bez ugljena",
  "everyone stays indoors for a year": "godinu dana svi ostaju unutra",
  "a bridge is built": "gradi se most",
  "the mill is turned into flats": "mlin postaje stanovi",
  "the trams stop running": "tramvaji prestaju voziti",

  // ---- ono maleno iz djetinjstva ----------------------------------------
  "being laughed at by the whole table": "smijeh cijelog stola",
  "the door closing": "vrata koja se zatvaraju",
  "not being believed": "to što ti nisu vjerovali",
  "coming last, in front of everyone": "zadnje mjesto, pred svima",
  "the word he used": "riječ koju je upotrijebio",
  "a promise about Saturday": "obećanje za subotu",
  "the silence after the question": "tišina nakon pitanja",
  "being told you were fine": "to što su rekli da si dobro",

  // ---- škola -------------------------------------------------------------
  "arithmetic": "računanje", "geography": "zemljopis", "history": "povijest",
  "biology": "biologija", "the other language": "onaj drugi jezik",
  "chemistry": "kemija", "physics": "fizika", "literature": "književnost",

  // ---- obitelj i ono što od nje dolazi ----------------------------------
  "You": "Ti", "Mother": "Majka", "Father": "Otac",
  "Grandmother": "Baka", "Grandfather": "Djed", "Ancestor": "Predak",
  "hope": "nada",
  "fear_of_the_dark": "strah od mraka",
  "stubbornness": "tvrdoglavost",
  "worry": "briga",
  "posture": "držanje",
  "silence": "šutnja",
  "recipe": "recept koji nikad nije zapisan",
  "eyes": "oči",
  "patience": "strpljenje",
  "a way with people": "dar za ljude",

  // ---- što se dogodilo ---------------------------------------------------
  "says a word, on purpose": "izgovara riječ, namjerno",
  "starts school": "kreće u školu",
  "leaves school with a certificate stating that you can be taught":
    "izlazi iz škole s potvrdom da se može podučiti",
  "falls in love, silently": "zaljubljuje se, u tišini",
  "first job": "prvi posao",
  "moves out for good": "odlazi zauvijek",
  "becomes a parent, and promises not to": "postaje roditelj i obećava da neće",
  "stops speaking to someone": "prestaje razgovarati s nekim",
  "your father dies": "umire mu otac",
  "your mother dies": "umire mu majka",
  "stops going to work": "prestaje ići na posao",
  "does not get up": "ne ustaje",
  "a child": "dijete",

  // ---- razdoblja ---------------------------------------------------------
  "infant": "dojenče", "child": "dijete", "teenager": "tinejdžer",
  "young": "mladost", "middle": "srednje godine", "later": "kasnije godine",
  "old": "starost", "late": "duboka starost",

  // ---- kamo je otišlo ----------------------------------------------------
  "work_cat": "posao", "worry_cat": "briga", "care_cat": "briga o drugima",
  "rest_cat": "odmor i ništa", "school_cat": "škola", "house_cat": "kuća",
  "body_cat": "tijelo", "regret_cat": "ono što nisi smio",
  "other_cat": "sve ostalo",
};

// chrome, in both languages
const UI = {
  en: {
    title: "A life", sub: "one run, whole",
    intro: "This runs the model from <b>satja/life</b> — a description of a life in Python whose loops end only because checking a condition costs a minute. Choose the conditions and it will live one, all at once.",
    century: "The century",
    centuryWhy: "How much happens that is not about you. Governments, borders, money, weather, war. A little of it can kill you.",
    conscience: "Conscience",
    conscienceWhy: "How often the list of things you meant to do is visible to you at all. At <i>sometimes</i>, about eight moments in a lifetime.",
    seed: "Seed", seedWhy: "The same seed and the same settings give the same life, exactly, every time.",
    roll: "roll", begin: "Live one", again: "Another",
    given: "What you were given", allotted: "years allotted. Nobody said so out loud.",
    inheritedFrom: "from", blameNote: "Everything above came down the family in the usual order. Nothing skipped a generation; some of it went round one.",
    theLife: "The life", replay: "watch it again",
    gridNote: "One square a year, darker the fuller. Click one.",
    mostly: "mostly", thoughtOf: "thought mostly about", thatYear: "that year",
    account: "The account", whereItWent: "Where it went",
    awakeLine: "%1 awake and doing something, out of %2.",
    worstLine: "tries on the worst night — at %1, finally asleep at %2",
    stillMeaning: "Still meaning to", meantNote: "The list was in view",
    times: "times", outside: "Meanwhile, outside",
    died: "Died at", at: "at", gotUp: "having got up", timesUp: "times",
    inTheYearOf: "in the year of",
    thoughts: "thoughts", different: "of them different",
    nightsAwake: "nights still awake at three",

    questions: "questions left open at school",
    neverUnderstood: "never understood", keptFromSchool: "kept from school",
    raisedIt: "Brought it up at", raisedAt: ", at someone who was not there",
    nothingLeft: "Nothing left on the list. This is rarer than it sounds.",
    noYear: "Not lived.", lang: "hrvatski",
  },
  hr: {
    title: "Život", sub: "jedan, cijeli",
    intro: "Ovo pokreće model iz <b>satja/life</b> — opis života u Pythonu čije petlje završavaju samo zato što provjera uvjeta troši minutu. Odaberi uvjete i proživjet će jedan, odjednom.",
    century: "Stoljeće",
    centuryWhy: "Koliko se toga događa što nema veze s tobom. Vlade, granice, novac, vrijeme, rat. Ponešto od toga te može ubiti.",
    conscience: "Savjest",
    conscienceWhy: "Koliko često ti je popis onoga što si namjeravao uopće vidljiv. Na <i>ponekad</i>, otprilike osam trenutaka u životu.",
    seed: "Sjeme", seedWhy: "Isto sjeme i iste postavke daju isti život, točno, svaki put.",
    roll: "baci", begin: "Proživi jedan", again: "Još jedan",
    given: "Što si dobio", allotted: "godina. Nitko to nije rekao naglas.",
    inheritedFrom: "od", blameNote: "Sve gore došlo je po obitelji uobičajenim redom. Ništa nije preskočilo naraštaj; ponešto ga je obišlo.",
    theLife: "Život", replay: "pogledaj ponovno",
    gridNote: "Jedan kvadratić po godini, tamniji što je punija. Klikni.",
    mostly: "uglavnom", thoughtOf: "najviše je mislio na", thatYear: "te godine",
    account: "Račun", whereItWent: "Kamo je otišlo",
    awakeLine: "%1 bio je budan i nešto radio, od ukupno %2.",
    worstLine: "pokušaja u najgoroj noći — u %1. godini, zaspao tek u %2",
    stillMeaning: "Još uvijek namjerava", meantNote: "Popis je bio vidljiv",
    times: "puta", outside: "U međuvremenu, vani",
    died: "Umro u", at: "u", gotUp: "ustavši ukupno", timesUp: "puta",
    inTheYearOf: "u godini kad je bilo:",
    thoughts: "misli", different: "različitih",
    nightsAwake: "noći budan u tri",

    questions: "pitanja ostalo otvoreno u školi",
    neverUnderstood: "nikad nije razumio", keptFromSchool: "od škole ostalo",
    raisedIt: "Iznio je to u", raisedAt: ", pred nekim tko nije bio ondje",
    nothingLeft: "Na popisu nije ostalo ništa. To je rjeđe nego što zvuči.",
    noYear: "Nije proživljeno.", lang: "english",
  },
};

const MONTHS_HR = ["sij", "velj", "ožu", "tra", "svi", "lip",
                   "srp", "kol", "ruj", "lis", "stu", "pro"];

// what a life divides into, for "where it went"
const CATEGORY = {
  work: ["working", "working, still", "going to work", "how to look busy",
         "looking for work", "answering messages", "answering the message",
         "applying", "waiting for an answer", "driving somewhere",
         "going back to it", "starting something", "quitting something"],
  worry: ["worrying about money", "worrying about someone else", "sleeping badly",
          "being embarrassed", "waiting for the phone", "having the same argument",
          "arguing", "cancelling", "reading the news too closely",
          "listening for news", "listening for the all-clear",
          "saying nothing at dinner", "slamming a door",
          "counting it again", "going without", "queueing", "explaining yourself",
          "seeing fewer friends", "lying awake in the heat", "crying"],
  care: ["carrying someone who is asleep", "reading the same book aloud",
         "looking after someone", "being needed", "going to funerals",
         "calling home, briefly", "sending what you can", "being visited",
         "loving someone who does not know", "falling in love"],
  rest: ["sleeping", "being bored", "waiting", "sitting", "sitting in the sun",
         "sitting in the shade", "doing nothing, on purpose", "being at the sea",
         "reading half a book", "eating outside", "going to the water",
         "sleeping in the afternoon", "staying up too late", "sitting in the dark with the shutters closed",
         "watching cartoons", "watching the news", "listening to the same song",
         "playing until it is dark", "walking for the sake of it", "walking slowly",
         "being outside again", "looking at photographs", "telling the story again",
         "reading the same page twice", "staying in", "staying indoors",
         "drinking too much", "going somewhere cheap", "riding a bike",
         "running", "collecting stones", "drawing a house", "eating",
         "breaking something", "standing in the doorway of a room",
         "laughing at nothing", "opening the windows", "watching it get dark early"],
  school: ["going to school", "doing the homework", "handing it in",
           "lying about homework", "studying the night before", "asking why",
           "long division", "the other language, badly", "the word for window",
           "how to sit through things"],
  house: ["fixing the same thing again", "getting it repaired", "paying the bill",
          "taking the bins out", "renewing the documents", "carrying something heavy",
          "watering the plants", "keeping warm", "keeping one room warm",
          "carrying things upstairs", "drying it out", "boarding up the windows",
          "putting something aside", "moving out", "going the new way",
          "walking it instead", "staying put", "going to look at it"],
  body: ["going to the doctor", "going to the check-up", "taking the pills",
         "being fed", "being carried", "being put down again",
         "putting it in your mouth", "staring at the lamp", "sleeping in the car",
         "waiting for it to get light", "looking in the mirror",
         "not recognising the street"],
  regret: ["checking the phone at three in the morning", "saying it out loud",
           "comparing", "keeping score", "reading the comments",
           "replying immediately", "looking back too long", "having one more",
           "bringing it up again"],
};

const CAT_ORDER = ["work", "rest", "care", "worry", "house", "school",
                   "body", "regret", "other"];
const CAT_OF = {};
for (const [cat, names] of Object.entries(CATEGORY)) for (const n of names) CAT_OF[n] = cat;

function say(text, lang) {
  if (lang !== "hr" || text === undefined || text === null) return text;
  if (HR[text]) return HR[text];
  // scars arrive already composed, and so does the one kept promise
  if (text.endsWith(", again")) {
    const base = text.slice(0, -", again".length);
    return (HR[base] || base) + ", opet";
  }
  if (text.startsWith("gets round to it — ")) {
    const base = text.slice("gets round to it — ".length);
    return "stigao je do: " + (HR[base] || base);
  }
  if (text.startsWith("raises it — ")) return text;   // rebuilt in the app
  if (text.startsWith("average mark: ")) {
    return "prosjek: " + text.slice("average mark: ".length);
  }
  return text;
}
